# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bankService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62\x61nkService.proto\x12\x0b\x42\x61nkService\"E\n\x0f\x43ustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"2\n\rBranchRequest\x12\x11\n\tbranch_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"3\n\x0fResponseMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"!\n\x0c\x42\x61lanceQuery\x12\x11\n\tbranch_id\x18\x01 \x01(\x05\x32\xc8\x03\n\x0b\x42\x61nkService\x12I\n\x0bMsgDelivery\x12\x1c.BankService.CustomerRequest\x1a\x1c.BankService.ResponseMessage\x12@\n\x05Query\x12\x19.BankService.BalanceQuery\x1a\x1c.BankService.ResponseMessage\x12\x46\n\x08Withdraw\x12\x1c.BankService.CustomerRequest\x1a\x1c.BankService.ResponseMessage\x12\x45\n\x07\x44\x65posit\x12\x1c.BankService.CustomerRequest\x1a\x1c.BankService.ResponseMessage\x12N\n\x12Propagate_Withdraw\x12\x1a.BankService.BranchRequest\x1a\x1c.BankService.ResponseMessage\x12M\n\x11Propagate_Deposit\x12\x1a.BankService.BranchRequest\x1a\x1c.BankService.ResponseMessageB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bankService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _globals['_CUSTOMERREQUEST']._serialized_start=34
  _globals['_CUSTOMERREQUEST']._serialized_end=103
  _globals['_BRANCHREQUEST']._serialized_start=105
  _globals['_BRANCHREQUEST']._serialized_end=155
  _globals['_RESPONSEMESSAGE']._serialized_start=157
  _globals['_RESPONSEMESSAGE']._serialized_end=208
  _globals['_BALANCEQUERY']._serialized_start=210
  _globals['_BALANCEQUERY']._serialized_end=243
  _globals['_BANKSERVICE']._serialized_start=246
  _globals['_BANKSERVICE']._serialized_end=702
# @@protoc_insertion_point(module_scope)
